export enum Categories {
    ALL = "all",
    HORROR = "horror",
    FANTASY = "fantasy",
    SCIFI = "science fiction",
    MYSTERY = "mystery",
    ROMANCE = "romance",
    THRILLER = "thriller",
    ACTION = "action",
    ADVENTURE = "adventure",
    CHILDREN = "children",
    COMEDY = "comedy",
    DRAMA = "drama",
    CRIME = "crime",
    FICTION = "fiction",
    BIOGRAPHY = "biography",
    SELF_HELP = "self-help",
    SCIENCE = "science",
}

